server.port: 8086

solon.app:
  name: 'demo-app'
  group: 'demo'

solon.config:
  load:
    - db.yml

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
config.env: "dev"

solon.dataSources:
  db_order!:
    class: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: "jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8"
    username: "${db.user}"
    password: "${db.password}"
