server.port: 8086

solon.app:
  name: 'demo-app'
  group: 'demo'

solon.config:
  load:
    - db.yml

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO
config.env: "dev"
