server.port: 8080

solon.app:
  name: 'demo-app'
  group: 'demo'

solon.logging:
  appender:
    console:
      level: INFO
    file:
      level: INFO

solon.dataSources:
  db_order!: #数据源命名，且加类型注册（即默认）
    class: "com.zaxxer.hikari.HikariDataSource" #数据源类
    jdbcUrl: "jdbc:mysql://111.111.111.111:23306/testPic?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true"
    driverClassName: "com.mysql.jdbc.Driver"
    username: "root"
    password: "root"
